### ISSUE TITLE
Fix Login window is not centered

### ISSUE THREAD

**Issue by paoloose** [live-houses/live-houses#1]
Couldn't center the login window, I tried to wrap the whole set of inputs, button and "Inicio de sesión" text but I'm not sure on how to style it correctly.

I trust the fxml man knows how to fix it

![Image](https://github.com/live-houses/live-houses/assets/98111143/f4024d76-a5aa-4e88-8da3-14cb51796858)

**Comment by paoloose** [comment]
By the way now all controllers are placed into the `controllers/` directory

**Comment by luedu1103** [comment]
I think we can use css to style the fxml, but I will check that tomorrow

**Comment by luedu1103** [comment]
More difficult than I thought....
Let's continue without centering the login

**Comment by paoloose** [comment]
fxml man has fallen 😿
marking the task as not planned

**Comment by paoloose** [comment]
closed thanks to https://github.com/live-houses/live-houses-admin/pull/1
