### ISSUE TITLE
Setup the project in your local machines

### ISSUE THREAD

**Issue by paoloose** [live-houses/live-houses#2]
The project currently uses Java 17 and Java FX

When opening from vscode, remember to install the following extensions

![image](https://github.com/live-houses/live-houses/assets/98111143/1f121aa0-c522-4777-a9a1-628f03abb833)

![image](https://github.com/live-houses/live-houses/assets/98111143/a9800f5b-d45b-432e-a27e-6a35c181bf20)

The dependencies for the project are listed in [`live-houses/app/build.gradle`](https://github.com/live-houses/live-houses/blob/2a81347b863995a5d5d596e3589fab69d91216fc/app/build.gradle#L18-L27).

https://github.com/live-houses/live-houses/blob/2a81347b863995a5d5d596e3589fab69d91216fc/app/build.gradle#L18-L27

Your gradle and IDE should be able to detect and install them automatically from the Maven repositories

Run the project with

```bash
# with gradle installed in your system
gradle run

# or with gradlew
./gradlew run
```

In the near future we may also have a database and backend server

This issue will be closed when all the members share a screenshot with the project running on their machines 

If you have any problem, consult it with the team :)

Checks (edit the comment or click the checkbox to mark this as done)

- [x] @luedu1103 
- [X] @RathiaRobsBobs 
- [x] @pandadiestro 
- [x] @AoiNabi 
- [X] @paoloose

**Comment by paoloose** [comment]
In order to mark your task as complete, edit my issue comment. You may also want to provide an image of the window application running on your machine 

![image](https://github.com/live-houses/live-houses/assets/98111143/c7f4a131-6b71-4453-a3d0-69259b17c434)

**Comment by luedu1103** [comment]
Please, refrain of blaming your companions :,v

**Comment by RathiaRobsBobs** [comment]
so how do i install the dependencies

**Comment by paoloose** [comment]
they should be installed automatically if you issue the 'gradle run' command in your terminal, assuming you've already installed gradle

**Comment by RathiaRobsBobs** [comment]
![Imagen de WhatsApp 2023-10-13 a las 13 32 01_6617f505](https://github.com/live-houses/live-houses/assets/124403825/830cabaf-fd3a-46b0-b743-40d1168081ab)

voilá, the thing ran successfully

**Comment by luedu1103** [comment]
Hi, I had to reajust some things with the code so it can run in my machine, here's the proof

![image](https://github.com/live-houses/live-houses/assets/123672027/7ae67b45-1d36-4ece-a24e-4f631def3140)

I've already push the changes in the gui branch

**Comment by paoloose** [comment]
@luedu1103 the gui branch is pretty much outdated now, I think we should delete both the gui and cli branch and just keep the main branch as should be done in tronco development

**Comment by pandadiestro** [comment]
I did run it but `gradle run` with current version of gradle at debian testing repos (4.4.1-20) throws the following exception

```sh
> Failed to apply plugin [id 'org.openjfx.javafxplugin']
   > This plugin requires Gradle 6.1+
```

The gradlew script works as expected, though.

**Comment by paoloose** [comment]
nice

**Comment by AoiNabi** [comment]
Hi, I ran the program in my machine, here's the proof

![image](https://github.com/live-houses/live-houses/assets/137377872/687aa7f3-6716-4c00-a707-5c0f4ac74b49)
