### ISSUE TITLE
🎭 Livehouse development 🎭

### ISSUE THREAD

**Issue by paoloose** [live-houses/live-houses#3]
Hey @InkAmelio, @RathiaRobsBobs, @luedu1103, @pandadiestro

we'll start with the active development of the live houses project

An issue-oriented software development with the following guidelines

- every contribution, feature, bug, design will be addressed as an 'issue'
- any person can create and assign issues
- any person can review and ask for reviews within an issue
- do you want to work on something? create and self-assign an issue for yourself :)
- keep the issues manageable and straightforward
- move your task status to `In Progress`, `Help needed`, `Done` accordingly

This is very close of how open source development works

Tasks can be created from here <https://github.com/orgs/live-houses/projects/1>

![image](https://github.com/live-houses/live-houses/assets/98111143/8d6746fb-68dd-438c-b320-8716b1bca75c)

The idea is that we can follow the work of each other and the project progress over time

Remember that this is for learning, thus your tasks can be hard-coded, over engineered, very simple solutions, whatever you can come up with to solve the problem, just always remember asking for help and guidance from your team

First task <https://github.com/live-houses/live-houses/issues/2>

![](https://raw.githubusercontent.com/live-houses/live-houses/main/assets/logo.png)

**Comment by RathiaRobsBobs** [comment]
fine
