### ISSUE TITLE
Add the database UML diagrams

### ISSUE THREAD

**Issue by paoloose** [live-houses/live-houses#7]
Before starting to migrate the current fake database to a PostgreSQL instance, we need to add the diagrams we've created.

I've setup a new directory to put all the Livehouse designs: https://github.com/live-houses/live-houses/tree/main/design

If you want to also document the database schema in the main README.md or to store the generated `.sql` file at some place, I leave that at your disposal

![Image](https://avestura.dev/_next/image?url=%2Fstatic%2Fimages%2Fposts%2Fpostgres-meme%2Fpostgres-meme.jpg&w=1080&q=75)

from <https://avestura.dev/blog/explaining-the-postgres-meme>

**Comment by pandadiestro** [comment]
The database diagram was [added!](https://github.com/live-houses/live-houses/pull/8#issue-1943889992), I also added it to the temporal DigitalOcean remote server for testing purposes.
