### ISSUE TITLE
Connect the Login with the Database

### ISSUE THREAD

**Issue by luedu1103** [live-houses/live-houses#9]
I will be adding some functionality to the gui similar to the cli we had at the beginning.

**Comment by paoloose** [comment]
fxml man i trust on you

**Comment by luedu1103** [comment]
is this done ?

**Comment by paoloose** [comment]
I think it is, what about merging the login-do-something branch with main?

**Comment by paoloose** [comment]
closed by https://github.com/live-houses/live-houses-admin/pull/1
